const C = {
    SET_SENDING: 'SET_SENDING',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_ERROR: 'AUTH_ERROR',
    LOGOUT: 'LOGOUT',
    GET_CATALOG: 'GET_CATALOG',
    GET_ITEM: 'GET_ITEM',
    SET_LOADING: 'SET_LOADING',
    REMOVE_ITEM: 'REMOVE_ITEM',
    EDIT_ITEM: 'EDIT_ITEM',
    REQ_RES: 'REQ_RES',
    CLEAR_FORM: 'CLEAR_FORM'
}

export default C